### ISSUE TITLE
People - Normalizing Thumbnail Photos

### ISSUE THREAD

**Issue by fcjou** [uwdub/web-dub#103]
Find a way to easily generate thumbnails for the People page. This could be done manually in Photoshop, but we are looking for a method that is more easily transferable for maintenance purposes.

Features:
- Circular border (this can be done in Bootstrap)
- Square dimensions (100x100)
- Centered on the face
- Greyscale

Part of #99

**Comment by fcjou** [comment]
The best solution I have found so far is using the [Cloudinary API](http://cloudinary.com/). 

This API basically has all the features that we need in order to generate the image transformations. We can either do this:
- Dynamically (but the caveat is that all the images need to be hosted and pulled from the Cloudinary cloud)
- Semi-manually (generate transformations and then save them to our library)

More info [here](http://cloudinary.com/documentation/image_transformations#face_detection).

**Comment by jayfo** [comment]
Support for Cloudinary normalization of images added in #266.
