### ISSUE TITLE
Reorganize Seminars

### ISSUE THREAD

**Issue by fcjou** [uwdub/web-dub#108]
The idea is to replace the Google Calendar with our own file structure and look.

- [x] Create preliminary seminar files (files for Winter 2015 were added #106)
- [x] Create sidebar layout for Current/Previous Seminars. Previous Seminars will be a separate page.
- [x] Create a filter that determines if a seminar file is current or previous.
- [x] Current/Previous seminar pages will include: name, affiliation, title, date, time, and location.
- [x] Seminar sub-pages will also include: abstract, bio, video (optional)
- [x] Display info on the next upcoming seminar, and a link to the calendar page on the Front page.
- [ ] Create seminar files for all previous seminars from the Google Calendar (finish migration)
- [ ] Filter Previous Seminars by year, and have the sidebar automatically update. Implement pagination.
- [x] Some seminar file entries may be incomplete (a placeholder with name and date, but no title). Figure out some system to include 'TBD' placeholders when fields are incomplete.

Adding new seminar content:
- [x] The people in charge of creating/updating new seminar information will need to submit a pull request. Initially provide a template. Eventually we may create a form to make submission easier.
- [ ] Find some way to deal with the issue of 'smart quotes'.

Post-seminar content:
- [x] Create a video field in the seminar file. Include the video embed on the seminar page if available. TODO: make embed responsive to small screen size
- [ ] Contact the person in charge of uploading the video (currently the MHCID Web Coordinator). They will be in charge of additionally adding the Vimeo video id to the seminar file.

**Comment by fcjou** [comment]
Additional items:
- Some seminar file entries may be incomplete (a placeholder with name and date, but no title). Include 'TBD' placeholders when fields are incomplete.
- The front page will display info on the next upcoming seminar, and a link to the calendar page.

**Comment by jayfo** [comment]
Closing issues to organize work we're actually doing.

Created #147 based on this.
