### ISSUE TITLE
"Build" Image Flipped

### ISSUE THREAD

**Issue by jayfo** [uwdub/web-dub#154]
Was this intentional?

> I just noticed that the one of the breadboard is flipped — look at the silkscreen labels on the bone board!

I hadn't noticed, but now can't help but notice.  ;)

**Comment by fcjou** [comment]
Oh! I had flipped it originally thinking the flipped image created a line that directed your eye to the right, and that felt more natural... In hindsight I realize how even more unnatural the backwards labels are! Fixing that now.

**Comment by jayfo** [comment]
Fixed in #157.
