### ISSUE TITLE
Decide Regarding dub-studies Mailing List

### ISSUE THREAD

**Issue by jayfo** [uwdub/web-dub#17]
The DUB list is being used to advertise studies, which detracts from the value density of the list.

When we publish the lists, we should be clear on this. Perhaps also create a studies list so people can opt-in to these types of emails.

**Comment by jayfo** [comment]
So I think I feel like a dub-studies list would be appropriate.

Let's raise this with a few people.

**Comment by jayfo** [comment]
We currently have these lists, with obvious purposes:

- dub
- dub-students
- dub-faculty

This list gets less use, but we should keep it:

- dub-social

These lists get much less use, approaching nil:

- dub-alumni: I propose we retire this, until we are generally more organized on alumni
- dub-staff: I propose we retire this

These are special purpose lists:

- speak
- dub-exec
- mhcid-exec
- dub-web

I propose we create:

- dub-studies: And slowly work toward moving study announcements onto that list

Thoughts from people like @smunson, @andyjko

**Comment by andyjko** [comment]
Agreed that dub-alumni and dub-staff are kind of useless right now and don't need to exist.

dub-studies could be DOA unless there are people who are actually subscribed to the list. Otherwise people will just continue to spam dub@.

**Comment by jayfo** [comment]
Agree on we need to plan for dub-studies. Let's assume we start moderating the main dub lists in order to get that traffic under control. Then we have a few choices:

- Opt-out: Sign everybody up, send an email on how to unsubscribe.

- Opt-in: Send a big email encouraging people to sign up. Repeat on a yearly basis.

- Opt-in: Allow studies to continue to go to dub for a while, with the requirement that people who recruit through the list have participants sign up for dub-studies with the understanding that we'll stop agreeing to forward at some point. Perhaps pair with something above.

Thoughts?

**Comment by jayfo** [comment]
I realize the question of dub-studies has nothing to do with getting us launched. So I have renamed this issue to focus on the question of dub-studies. And I have created #61 to focus on getting the established lists documented.

**Comment by andyjko** [comment]
I think people wouldn't be unhappy if they were automatically subscribed to a new list. I'd guess that maybe 5% of the people on DUB are actually interested in participating. I think it has to be opt-in.

Ideally, we'd be telling undergrads in our classes to sign up to engage in research, then Ph.D. students and faculty could recruit them. Perhaps we make the list, tell everyone teaching an HCI course about the list for about 3 months, and then turn on moderation to dub and start redirecting people to the studies list.
