### ISSUE TITLE
Visibility of Videos

### ISSUE THREAD

**Issue by jayfo** [uwdub/web-dub#179]
Andy Davidson suggests:

> How about a link under “Connect with DUB” to our Vimeo channel (vimeo.com/designusebuild/videos) so people can get easily to the history without diving into the previous calendar entries?

I agree that perhaps videos are not as readily surfaced as they could be. I'm less sure the answer is a link out. We're a website, not a link farm. And I don't want us just slapping links everywhere.

I might prefer we fix our previous seminars format so videos are more accessible. Does that potentially resolve this? If we used tbd_video to put an icon or something on the previous seminars page, making it more apparent that some have videos?

**Comment by ahdavidson** [comment]
James, I hardly think one more link to a place where people can find and follow our stuff implies a link farm, does it?

We now have:

- Learn about DUB. -- which is just a short cut to the About page on the site 
- Join the DUB mailing lists.
- Follow us on Twitter.

I'm just suggesting adding:

- Watch our seminar videos

to that list.

As an exercise, I suggest trying to find one of the videos to watch and see how many clicks it takes from the home page.

**Comment by jayfo** [comment]
Oh I clearly agree they're not easily surfaced right now.

But just dumping out to Vimeo abandons any notion we're developing content here. I'd rather fix it here.

Oddly enough, I object less if we replace the Twitter link with a Vimeo link. At least we have some content on Vimeo, while the Twitter account is still fairly dormant.

**Comment by smunson** [comment]
From Dan Weld:

>  Also, while I know I found the online recording of my talk a week ago, I just failed to find it after several minutes of searching – it occurs to me that more people would watch these videos (quite fantastic resources, my talk excluded) if
> 
> - there was a link to the dub video channel on the dub home page
> - Each calendar entry (in previous seminars) included a link to the recorded talk
> 
> I know the dub website is a volunteer activity and it may be too hard to do #2, but #1 seems easy (I couldn’t remember if they were hosted at video lectures.net or where and couldn’t find the channel by searching)

**Comment by jayfo** [comment]
Per discussion today, let's try:

- add "Follow us on Vimeo"
- reward "Tweet @uwdub"
- move "Learn about DUB" to "What is DUB?" column
- match "View Full Calendar" icon language

- apply your experimentation with removing time / place on archived seminars
- try linking to video in that same space (i.e., we'll never have both)

**Comment by jayfo** [comment]
We've added a Vimeo link to the front page under Connect with DUB:

http://dub.washington.edu/index.html

Videos are embedded in prior seminars:

http://dub.washington.edu/seminars/2016-02-03.html

We have been experimenting with some indication of which seminars have videos from the previous seminars page, but were unable to find an indication that we were visually happy with.

I'd like to declare this closed for now. @smunson ?  @ahdavidson ?

**Comment by smunson** [comment]
Thanks - I think this makes them much easier to find.

I agree about eventually coming up with an indicator on the previous seminars page (maybe a tiny grey version of this icon https://thenounproject.com/search/?q=tv&i=53833 next to the speaker name? Could also put speaker and organization on the same line to save space), but these are nice improvements. 

sean

**Comment by ahdavidson** [comment]
Yes, thanks.

And thanks for having a process and responding to requests.

.andy
