### ISSUE TITLE
Revise Mission on Medium to be Consistent

### ISSUE THREAD

**Issue by jayfo** [uwdub/web-dub#488]
As part of the getting involved edits, I tweaked mission text today, saying:

> Our mission is to bring together an interdisciplinary group of people to share ideas, collaborate on research, and advance teaching related to the interaction between design, people, and technology. 

Do we want that same tweak here:

https://medium.com/hci-design-at-uw/about

**Comment by jayfo** [comment]
@smunson

**Comment by smunson** [comment]
Done
