### ISSUE TITLE
Static Content: Getting Involved

### ISSUE THREAD

**Issue by fcjou** [uwdub/web-dub#93]
Create content for 'Getting Involved'

This content is split up into sections:
- Mailing List (there is also a separate 'Mailing List' page with the same info)
- Seminar (this is brief blurb that has a link to the 'Calendar' page)
- Current Students, Researchers and Faculty
- Prospective Students (Admissions?)

Thoughts on these sections and their titles?

Other people to consider:
- Undergrads
- Industry Sponsors

We also need to decide on who to be the point of contact for people interested in DUB.

**Comment by jayfo** [comment]
Fixed in #90
