### ISSUE TITLE
Static Content: About DUB

### ISSUE THREAD

**Issue by fcjou** [uwdub/web-dub#96]
Currently this page contains:
- Several paragraphs talking about DUB and its history.

Also (will commit this soon):
- A listing of all the involved DUB units.
- Previously there was graduate program info on this page. This will be moved to 'Getting Involved'.

@jayfo I believe you mentioned adding information on the DUB structure (leadership and units). Is this information still being finalized, or is it available?

**Comment by jayfo** [comment]
Pushed a version in #125. Good enough for feedback.
