### ISSUE TITLE
Implement People

### ISSUE THREAD

**Issue by fcjou** [uwdub/web-dub#99]
For the internal launch, we are going with:
- Round-frame black-and-white photo
- Name (hyperlink to personal site)
- Department(s)

Eventually there will be sub-pages with additional info such as:
- A short blurb (maybe - but this may need maintenance so maybe not)
- Publications

**Comment by fcjou** [comment]
Some of the data (in particular, unit format) are inconsistent across listings - we will need to clean up the database at some point..

**Comment by jayfo** [comment]
Closing to make clear things we're actually working on.
